package Shapes.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Canvas = 0;
  public static final int Circle = 1;
  public static final int Color = 2;
  public static final int ColorReference = 3;
  public static final int Shape = 4;
  public static final int Square = 5;
  public static final int Triangle = 6;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xc619ddb3dc464bbdL, 0x8185cc1ec0a4178cL);
    builder.put(0x2d1e18fc5e6ccfb3L, Canvas);
    builder.put(0x2d1e18fc5e6ccf98L, Circle);
    builder.put(0x2d1e18fc5e7683f6L, Color);
    builder.put(0x2d1e18fc5e7930daL, ColorReference);
    builder.put(0x2d1e18fc5e6ccf96L, Shape);
    builder.put(0x2d1e18fc5e6ccf9eL, Square);
    builder.put(0x2d1e18fc5e6ccfa4L, Triangle);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
